import Head from "next/head"
import Link from "next/link"

import { main } from '@/styles/Layout.module.scss'

const Layout = ({ children }) => {
  return (
    <>
        <Head>
            <title>Cat Fact App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
        <header>
            <ul>
                <li>
                    <Link href='/'>Home</Link>
                    <Link href='/about'>About</Link>
                    <Link href='/contact'>Contact</Link>
                </li>
            </ul>
        </header>
        <main className={main} >
            {children}
        </main>
    </>
  )
}

export default Layout